export const ADD_TO_CART = 'ADD_TO_CART'
export const TOGGLE_BUTTON_PRODUCT = 'TOGGLE_BUTTON_PRODUCT'

export const ADD_QUANTITY = 'ADD_QUANTITY'
export const REMOVE_QUANTITY = 'REMOVE_QUANTITY'
export const REMOVE_TO_CART = 'REMOVE_TO_CART'